In [1]:
import numpy as np

In [2]:
matrix = np.arange(20).reshape(5,4)

In [3]:
matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [4]:
matrix.mean()

9.5

In [5]:
matrix ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225],
       [256, 289, 324, 361]])

In [6]:
matrix[:3, 2:4]
# first rows, then columns

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [8]:
matrix[:3, 2:4].mean()
#can apply methods to just a selection

6.5

In [9]:
matrix.mean(axis=0)
# average of each column

array([ 8.,  9., 10., 11.])

In [10]:
import pandas as pd

In [12]:
df = pd.read_csv("/Users/bianca/Documents/GitHub/DAT-10-14/class material/Unit1/data/titanic.csv")

In [14]:
type(df)

pandas.core.frame.DataFrame

In [15]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [20]:
df['Survived'].mean()

0.3838383838383838

In [23]:
df[['Age', 'Survived']]

# output is a list of keys - rewriting of a dictionary so looking up two key values

Age  Survived
0    22.0         0
1    38.0         1
2    26.0         1
3    35.0         1
4    35.0         0
5     NaN         0
6    54.0         0
7     2.0         0
8    27.0         1
9    14.0         1
10    4.0         1
11   58.0         1
12   20.0         0
13   39.0         0
14   14.0         0
15   55.0         1
16    2.0         0
17    NaN         1
18   31.0         0
19    NaN         1
20   35.0         0
21   34.0         1
22   15.0         1
23   28.0         1
24    8.0         0
25   38.0         1
26    NaN         0
27   19.0         0
28    NaN         1
29    NaN         0
..    ...       ...
861  21.0         0
862  48.0         1
863   NaN         0
864  24.0         0
865  42.0         1
866  27.0         1
867  31.0         0
868   NaN         0
869   4.0         1
870  26.0         0
871  47.0         1
872  33.0         0
873  47.0         0
874  28.0         1
875  15.0         1
876  20.0         0
877  19.0         0
878   NaN         0
879  56.0         1
880  25.0         1
881  33.0         0
882  22.0         0
883  28.0         0
884  25.0         0
885  39.0         0
886  27.0         0
887  19.0         1
888   NaN         0
889  26.0         1
890  32.0         0

[891 rows x 2 columns]

In [24]:
num_cols = df.select_dtypes(number=np.)

df[num_cols][:100]

NameError: name 'num_cols' is not defined

In [26]:
df.iloc[:25, 2:9]

Pclass                                               Name     Sex   Age  \
0        3                            Braund, Mr. Owen Harris    male  22.0   
1        1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
2        3                             Heikkinen, Miss. Laina  female  26.0   
3        1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
4        3                           Allen, Mr. William Henry    male  35.0   
5        3                                   Moran, Mr. James    male   NaN   
6        1                            McCarthy, Mr. Timothy J    male  54.0   
7        3                     Palsson, Master. Gosta Leonard    male   2.0   
8        3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0   
9        2                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0   
10       3                    Sandstrom, Miss. Marguerite Rut  female   4.0   
11       1                           Bonnell, Miss. Elizabeth  female  58.0   
12       3                     Saundercock, Mr. William Henry    male  20.0   
13       3                        Andersson, Mr. Anders Johan    male  39.0   
14       3               Vestrom, Miss. Hulda Amanda Adolfina  female  14.0   
15       2                   Hewlett, Mrs. (Mary D Kingcome)   female  55.0   
16       3                               Rice, Master. Eugene    male   2.0   
17       2                       Williams, Mr. Charles Eugene    male   NaN   
18       3  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0   
19       3                            Masselmani, Mrs. Fatima  female   NaN   
20       2                               Fynney, Mr. Joseph J    male  35.0   
21       2                              Beesley, Mr. Lawrence    male  34.0   
22       3                        McGowan, Miss. Anna "Annie"  female  15.0   
23       1                       Sloper, Mr. William Thompson    male  28.0   
24       3                      Palsson, Miss. Torborg Danira  female   8.0   

    SibSp  Parch            Ticket  
0       1      0         A/5 21171  
1       1      0          PC 17599  
2       0      0  STON/O2. 3101282  
3       1      0            113803  
4       0      0            373450  
5       0      0            330877  
6       0      0             17463  
7       3      1            349909  
8       0      2            347742  
9       1      0            237736  
10      1      1           PP 9549  
11      0      0            113783  
12      0      0         A/5. 2151  
13      1      5            347082  
14      0      0            350406  
15      0      0            248706  
16      4      1            382652  
17      0      0            244373  
18      1      0            345763  
19      0      0              2649  
20      0      0            239865  
21      0      0            248698  
22      0      0            330923  
23      0      0            113788  
24      3      1            349909

In [27]:
df.iloc[:25, [0,3,8,10]]

#if you want to grab irregular columns

PassengerId                                               Name  \
0             1                            Braund, Mr. Owen Harris   
1             2  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2             3                             Heikkinen, Miss. Laina   
3             4       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4             5                           Allen, Mr. William Henry   
5             6                                   Moran, Mr. James   
6             7                            McCarthy, Mr. Timothy J   
7             8                     Palsson, Master. Gosta Leonard   
8             9  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)   
9            10                Nasser, Mrs. Nicholas (Adele Achem)   
10           11                    Sandstrom, Miss. Marguerite Rut   
11           12                           Bonnell, Miss. Elizabeth   
12           13                     Saundercock, Mr. William Henry   
13           14                        Andersson, Mr. Anders Johan   
14           15               Vestrom, Miss. Hulda Amanda Adolfina   
15           16                   Hewlett, Mrs. (Mary D Kingcome)    
16           17                               Rice, Master. Eugene   
17           18                       Williams, Mr. Charles Eugene   
18           19  Vander Planke, Mrs. Julius (Emelia Maria Vande...   
19           20                            Masselmani, Mrs. Fatima   
20           21                               Fynney, Mr. Joseph J   
21           22                              Beesley, Mr. Lawrence   
22           23                        McGowan, Miss. Anna "Annie"   
23           24                       Sloper, Mr. William Thompson   
24           25                      Palsson, Miss. Torborg Danira   

              Ticket Cabin  
0          A/5 21171   NaN  
1           PC 17599   C85  
2   STON/O2. 3101282   NaN  
3             113803  C123  
4             373450   NaN  
5             330877   NaN  
6              17463   E46  
7             349909   NaN  
8             347742   NaN  
9             237736   NaN  
10           PP 9549    G6  
11            113783  C103  
12         A/5. 2151   NaN  
13            347082   NaN  
14            350406   NaN  
15            248706   NaN  
16            382652   NaN  
17            244373   NaN  
18            345763   NaN  
19              2649   NaN  
20            239865   NaN  
21            248698   D56  
22            330923   NaN  
23            113788    A6  
24            349909   NaN

In [ ]:
#select any columns and rows and apply method to just that selection

In [29]:
df['Age'].mean()

29.69911764705882

In [31]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [32]:
df[['Fare', 'SibSp']].median()

Fare     14.4542
SibSp     0.0000
dtype: float64

In [34]:
df[['Fare', 'SibSp']][:100].median()

Fare     15.675
SibSp     0.000
dtype: float64

In [41]:
df.iloc[:,-4:].mode()

Ticket  Fare        Cabin Embarked
0      1601  8.05      B96 B98        S
1    347082   NaN  C23 C25 C27      NaN
2  CA. 2343   NaN           G6      NaN

In [43]:
df.iloc[:250,:3].mean()

PassengerId    125.500
Survived         0.344
Pclass           2.416
dtype: float64

In [59]:
df[df['Sex'] == 'female']['Sex'].count()

314

In [56]:
df[df['Sex'] == 'male']['Sex'].count()

577

In [57]:
df[df['Sex'] == 'female']
#just selects rows with 'females'

PassengerId  Survived  Pclass  \
1              2         1       1   
2              3         1       3   
3              4         1       1   
8              9         1       3   
9             10         1       2   
10            11         1       3   
11            12         1       1   
14            15         0       3   
15            16         1       2   
18            19         0       3   
19            20         1       3   
22            23         1       3   
24            25         0       3   
25            26         1       3   
28            29         1       3   
31            32         1       1   
32            33         1       3   
38            39         0       3   
39            40         1       3   
40            41         0       3   
41            42         0       2   
43            44         1       2   
44            45         1       3   
47            48         1       3   
49            50         0       3   
52            53         1       1   
53            54         1       2   
56            57         1       2   
58            59         1       2   
61            62         1       1   
..           ...       ...     ...   
807          808         0       3   
809          810         1       1   
813          814         0       3   
816          817         0       3   
820          821         1       1   
823          824         1       3   
829          830         1       1   
830          831         1       3   
835          836         1       1   
842          843         1       1   
849          850         1       1   
852          853         0       3   
853          854         1       1   
854          855         0       2   
855          856         1       3   
856          857         1       1   
858          859         1       3   
862          863         1       1   
863          864         0       3   
865          866         1       2   
866          867         1       2   
871          872         1       1   
874          875         1       2   
875          876         1       3   
879          880         1       1   
880          881         1       2   
882          883         0       3   
885          886         0       3   
887          888         1       1   
888          889         0       3   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
14                Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
19                             Masselmani, Mrs. Fatima  female   NaN      0   
22                         McGowan, Miss. Anna "Annie"  female  15.0      0   
24                       Palsson, Miss. Torborg Danira  female   8.0      3   
25   Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  female  38.0      1   
28                       O'Dwyer, Miss. Ellen "Nellie"  female   NaN      0   
31      Spencer, Mrs. William Augustus (Marie Eugenie)  female   NaN      1   
32                            Glynn, Miss. Mary Agatha  female   NaN      0   
38                  Vander Planke, Miss. Augusta Maria  female  18.0      2   
39                         Nicola-Yarred, Miss. Jamila  female  14.0      1   
40      Ahlin, Mrs. Johan (Johanna Persdotter Larsson)  female  40.0